### ISSUE TITLE
Check if it works on Windows and macOS, fix if necessary

### ISSUE THREAD

**Issue by pzmarzly** [pzmarzly/portforwarder-rs#2]
I don't have access to any of those OSes.

Maybe the project just compiles, maybe it needs to have its dependencies updated, maybe it needs some rewrite?

**Comment by nicbn** [comment]
Won't compile on Windows
https://pastebin.com/CpRmNHNf

**Comment by pzmarzly** [comment]
Thanks.

I initially thought [`get_if_addrs`](https://github.com/maidsafe-archive/get_if_addrs) was going to be a problem (perhaps different `struct`s representing the network interface, depending on the OS - but I just looked at the source code and it's not the case).

It makes a lot of sense for the Ctrl+C listener to be a problem. I think it would be enough to just rewrite this part:

https://github.com/pzmarzly/portforwarder-rs/blob/6649b28cdfbece7a79daad2c6eee5304ce519dfe/src/bin/pf.rs#L90-L106

to use the cross-platform [`ctrlc` crate](http://detegr.github.io/doc/ctrlc/).

I can work on it next week, unless you want to fix it yourself and open a PR.

**Comment by eutampieri** [comment]
I think I could have a look if you didn’t have time

**Comment by pzmarzly** [comment]
Sure, go ahead.

I consider the project done for me (it does all I wanted), so I'm not keen on spending time on it, but I would gladly merge working code, especially if it means making the project useful for more people.

**Comment by eutampieri** [comment]
Ok, on macOS compiles. I will check on Windows as soon as I have time
