### ISSUE TITLE
Error: "zsh: command not found: pf" on MacOS

### ISSUE THREAD

**Issue by EmanuelFaria** [pzmarzly/portforwarder-rs#5]
Installation of Crate and Portforwarder went fine (had to use git-clone for the latter), but ran into trouble customizing the ports.

Using either of these commands bellow, returned this error: `zsh: command not found: pf`

`pf any TCP/80/80 UDP/3000/2000 TCP/81/82`
`pf 192.168.254.107 TCP/8080/8080`

I'm using a Mac Powerbook Catalina OS version 10.15.7 (19H114)

Thanks

**Comment by EmanuelFaria** [comment]
Maybe it's because I don't know how to do either of these things? Can you help?

> 
> Rust is installed now. Great!
> 
> To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
> environment variable. Next time you log in this will be done
> automatically.
> 
> To configure your current shell, run:
> source $HOME/.cargo/env

When I try I get this error: 

> manny@Mannys-MacBook-Pro ~ % $HOME/.cargo/en
> zsh: no such file or directory: /Users/manny/.cargo/en

**Comment by pzmarzly** [comment]
Hi. The error means that zsh couldn't find `pf` binary in folders listed in `$PATH`.

You can see which folders zsh looks into via `echo $PATH`. Assuming you built portforwarder with `cargo build`, you can just move `target/release/pf` executable file to any of `$PATH`-listed folders.

Or, a better way would be to create a folder (e.g. `.cargo`, or `.local/bin`, or whatever name you want) and add it to `$PATH` by changing `.zshrc`. See https://coolestguidesontheplanet.com/how-to-add-to-the-shell-path-in-macos-using-terminal/

EDIT: the guide I linked to, on coolestguidesontheplanet.com, has an error - it says `.zsh`, while the correct file is named `.zshrc`

EDIT 2: The folder I mentioned in the readme text, `.cargo`, comes from the fact that `cargo install portforwarder-rs` by default installs the program to `~/.cargo/bin/pf` on Linux.
